/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 AIRMAX.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AIRMAX(props) {
  const { nodes, materials } = useGLTF('/AIRMAX.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.Texture} />
    </group>
  )
}

useGLTF.preload('/AIRMAX.gltf')
