/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cyberCity.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function CyberCity(props) {
  const { nodes, materials } = useGLTF('/cyberCity.gltf')
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={683} decay={2} position={[2.334, 8.504, 2.837]} rotation={[-0.833, 0.42, -0.355]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[21.682, 12.145, 0.6]} rotation={[-1.549, 1.102, 1.546]} />
      <pointLight intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <pointLight intensity={543.514} decay={2} position={[3.835, 1.478, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={543.514} decay={2} position={[3.835, 2.871, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={543.514} decay={2} position={[3.406, 3.443, -2.418]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={13897.655} decay={2} position={[3.406, 3.91, -2.8]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={543.514} decay={2} position={[3.835, 4.152, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={12185.587} decay={2} color="#00ffff" position={[2.681, 1.693, 0.506]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={3201.3} decay={2} color="#0800ff" position={[2.681, 2.208, 0.822]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={12185.587} decay={2} color="#00ffff" position={[0.647, 2.852, 0.463]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={543.514} decay={2} position={[2.259, 5.971, 1.034]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={543.514} decay={2} position={[2.259, 4.84, 1.034]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0, 0, 0.702]} scale={[4.696, 0.081, 4.055]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.008']} position={[2.709, 2.243, -0.327]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.010']} position={[0.982, 2.266, -0.327]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.009']} position={[2.709, 2.243, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.014']} position={[0, 0.083, -0.409]} scale={[4.696, 0.081, 2.949]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.012']} position={[2.723, 1.923, 0.583]} rotation={[0.184, 0, 0]} scale={[0.861, 1, 1]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[1.406, 2.04, 0.716]} scale={[0.308, 0.154, 0.133]}>
        <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.824, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.747, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.665, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.589, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-0.509, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-0.432, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-0.351, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-0.274, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-0.187, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-0.111, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-0.029, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} position={[0.048, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
      </mesh>
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[1.965, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[2.182, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[2.392, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[2.609, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[2.825, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[3.041, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} position={[3.252, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[3.468, 2.503, 0.784]} rotation={[1.765, 0, 0]} scale={[0.09, 1, 0.603]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[1.406, 2.04, 0.716]} scale={[0.308, 0.154, 0.133]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[1.406, 2.04, 0.716]} scale={[0.308, 0.154, 0.133]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[3.61, 2.04, 0.195]} rotation={[0, Math.PI / 2, 0]} scale={[0.308, 0.154, 0.133]}>
        <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[-0.824, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} position={[-0.747, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[-0.665, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} position={[-0.589, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} position={[-0.509, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} position={[-0.432, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder018.geometry} material={nodes.Cylinder018.material} position={[-0.351, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder019.geometry} material={nodes.Cylinder019.material} position={[-0.274, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} position={[-0.187, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} position={[-0.111, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} position={[-0.029, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} position={[0.048, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
      </mesh>
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[3.61, 2.382, 0.195]} rotation={[0, Math.PI / 2, 0]} scale={[0.308, 0.154, 0.133]}>
        <mesh geometry={nodes.Cylinder024.geometry} material={nodes.Cylinder024.material} position={[-0.824, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} position={[-0.747, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder026.geometry} material={nodes.Cylinder026.material} position={[-0.665, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder027.geometry} material={nodes.Cylinder027.material} position={[-0.589, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder028.geometry} material={nodes.Cylinder028.material} position={[-0.509, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder029.geometry} material={nodes.Cylinder029.material} position={[-0.432, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder030.geometry} material={nodes.Cylinder030.material} position={[-0.351, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder031.geometry} material={nodes.Cylinder031.material} position={[-0.274, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder032.geometry} material={nodes.Cylinder032.material} position={[-0.187, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder033.geometry} material={nodes.Cylinder033.material} position={[-0.111, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} position={[-0.029, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder035.geometry} material={nodes.Cylinder035.material} position={[0.048, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
      </mesh>
      <mesh geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} position={[3.62, 0.628, -0.249]} scale={[0.02, 0.467, 0.034]} />
      <mesh geometry={nodes.Cylinder037.geometry} material={nodes.Cylinder037.material} position={[3.62, 1.002, -0.408]} scale={[0.02, 0.467, 0.034]} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials['Material.003']} position={[3.701, 3.309, -0.795]} scale={[0.139, 3.279, 0.139]} />
      <mesh geometry={nodes.Cylinder039.geometry} material={nodes.Cylinder039.material} position={[3.687, 1.002, -1.143]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.467, 0.034]} />
      <mesh geometry={nodes.Cylinder040.geometry} material={nodes.Cylinder040.material} position={[3.687, 0.818, -1.258]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.368, 0.034]} />
      <mesh geometry={nodes.Cylinder041.geometry} material={nodes.Cylinder041.material} position={[3.687, 0.853, -1.453]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.385, 0.034]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[3.562, 0.483, -1.287]} scale={[0.353, 0.412, 0.353]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[3.477, 2.193, 0.19]} scale={[0.39, 0.455, 0.39]} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[3.156, 3.746, 0.665]} rotation={[Math.PI / 2, 0, 0]} scale={[0.359, 1, 0.767]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[2.344, 3.77, 0.665]} rotation={[Math.PI / 2, 0, 0]} scale={[0.354, 1, 0.767]} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[2.774, 3.908, 0.988]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.285, 1, 0.767]} />
      <mesh geometry={nodes.Cylinder043.geometry} material={nodes.Cylinder043.material} position={[0.634, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={nodes.Cylinder046.material} position={[2.49, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder049.geometry} material={nodes.Cylinder049.material} position={[-3.111, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder052.geometry} material={nodes.Cylinder052.material} position={[-1.256, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder055.geometry} material={nodes.Cylinder055.material} position={[5.142, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[3.65, 2.761, -1.253]} rotation={[0, Math.PI / 2, 0]} scale={[0.308, 0.154, 0.133]}>
        <mesh geometry={nodes.Cylinder056.geometry} material={nodes.Cylinder056.material} position={[-0.824, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder057.geometry} material={nodes.Cylinder057.material} position={[-0.747, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder058.geometry} material={nodes.Cylinder058.material} position={[-0.665, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder059.geometry} material={nodes.Cylinder059.material} position={[-0.589, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder060.geometry} material={nodes.Cylinder060.material} position={[-0.509, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder061.geometry} material={nodes.Cylinder061.material} position={[-0.432, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder062.geometry} material={nodes.Cylinder062.material} position={[-0.351, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder063.geometry} material={nodes.Cylinder063.material} position={[-0.274, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder064.geometry} material={nodes.Cylinder064.material} position={[-0.187, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder065.geometry} material={nodes.Cylinder065.material} position={[-0.111, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder066.geometry} material={nodes.Cylinder066.material} position={[-0.029, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder067.geometry} material={nodes.Cylinder067.material} position={[0.048, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
      </mesh>
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2.702, 0.523, 0.361]} scale={[0.842, 0.367, 0.31]} />
      <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[4.11, 3.645, -0.802]} rotation={[Math.PI / 2, 0, 0.017]} scale={[0.285, 1, 1.568]} />
      <mesh geometry={nodes.Cylinder042.geometry} material={nodes.Cylinder042.material} position={[3.687, 4.618, -1.106]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.385, 0.034]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[0.982, 2.181, -0.327]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cylinder044.geometry} material={nodes.Cylinder044.material} position={[0.968, 0.628, 0.704]} rotation={[0, Math.PI / 2, 0]} scale={[0.02, 0.467, 0.034]} />
      <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[3.243, 4.546, -0.002]} rotation={[Math.PI / 2, 1.387, -Math.PI / 2]} scale={[0.663, 0.705, 0.705]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[3.634, 4.959, 0.203]} rotation={[-0.005, 1.566, 0.005]} scale={[0.308, 0.154, 0.133]}>
        <mesh geometry={nodes.Cylinder045.geometry} material={nodes.Cylinder045.material} position={[-0.824, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder047.geometry} material={nodes.Cylinder047.material} position={[-0.747, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder048.geometry} material={nodes.Cylinder048.material} position={[-0.665, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder050.geometry} material={nodes.Cylinder050.material} position={[-0.589, -0.091, 0.798]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder051.geometry} material={nodes.Cylinder051.material} position={[-0.509, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder053.geometry} material={nodes.Cylinder053.material} position={[-0.432, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder054.geometry} material={nodes.Cylinder054.material} position={[-0.351, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder068.geometry} material={nodes.Cylinder068.material} position={[-0.274, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
        <mesh geometry={nodes.Cylinder069.geometry} material={nodes.Cylinder069.material} position={[-0.187, -0.091, 0.792]} scale={[0.018, 0.865, 0.073]} />
      </mesh>
      <mesh geometry={nodes.Cylinder070.geometry} material={nodes.Cylinder070.material} position={[3.574, 5.428, 0.318]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.184, 0.034]} />
      <mesh geometry={nodes.Cylinder071.geometry} material={nodes.Cylinder071.material} position={[3.574, 5.428, 0.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.184, 0.034]} />
      <mesh geometry={nodes.Cylinder072.geometry} material={nodes.Cylinder072.material} position={[3.574, 5.428, 0.101]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.184, 0.034]} />
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[3.168, 5.069, 0.696]} rotation={[Math.PI / 2, 0, 0]} scale={[0.168, 1, 1]} />
      <mesh geometry={nodes.Cylinder073.geometry} material={nodes.Cylinder073.material} position={[5.142, 0.536, 0.678]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder074.geometry} material={nodes.Cylinder074.material} position={[5.142, 0.536, -0.995]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder075.geometry} material={nodes.Cylinder075.material} position={[5.142, 0.536, -2.511]} scale={[0.094, 0.403, 0.094]} />
      <mesh geometry={nodes.Cylinder076.geometry} material={materials['Material.001']} position={[3.952, 2.957, 0.009]} rotation={[Math.PI / 2, 0, 0]} scale={[0.024, 0.666, 0.024]} />
      <mesh geometry={nodes.Cylinder077.geometry} material={materials['Material.001']} position={[3.576, 3.433, -1.787]} rotation={[Math.PI / 2, 0, 0]} scale={[0.024, 0.485, 0.024]} />
      <mesh geometry={nodes.Cylinder078.geometry} material={materials['Material.001']} position={[3.576, 3.433, -2.866]} rotation={[Math.PI / 2, 0, 0]} scale={[0.024, 0.485, 0.024]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.002']} position={[1.09, 2.266, -0.429]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.004']} position={[2.7, 2.243, -0.327]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.005']} position={[4.11, 3.645, -0.802]} rotation={[Math.PI / 2, 0, 0.017]} scale={[0.285, 1, 1.568]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.006']} position={[2.774, 3.908, 0.988]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.285, 1, 0.767]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.007']} position={[2.709, 2.243, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.007']} position={[2.709, 2.05, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.007']} position={[2.709, 2.05, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.007']} position={[2.709, 1.856, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.007']} position={[2.709, 1.649, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.007']} position={[2.709, 1.442, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials['Material.007']} position={[2.709, 1.257, -2.343]} scale={[0.861, 2.331, 1]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.011']} position={[2.745, 4.136, 0.679]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.428} />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials['Material.001']} position={[3.637, 2.841, 0.009]} rotation={[Math.PI / 2, 0, 0]} scale={[0.024, 0.666, 0.024]} />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials['Material.001']} position={[3.637, 1.429, 0.009]} rotation={[Math.PI / 2, 0, 0]} scale={[0.024, 0.666, 0.024]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.013']} position={[1.809, 4.785, 0.731]} rotation={[Math.PI / 2, 0, 0]} scale={0.383} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.013']} position={[1.809, 5.942, 0.663]} rotation={[Math.PI / 2, 0, 0]} scale={0.383} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.013']} position={[3.955, 4.095, -0.706]} rotation={[Math.PI / 2, 0, 0]} scale={0.383} />
      <mesh geometry={nodes.Cube043.geometry} material={materials['Material.014']} position={[0, 0.005, -0.409]} scale={[4.696, 0.081, 2.949]} />
      <mesh geometry={nodes.Cylinder081.geometry} material={nodes.Cylinder081.material} position={[3.871, 0.536, 2.351]} scale={[0.094, 0.403, 0.094]} />
    </group>
  )
}

useGLTF.preload('/cyberCity.gltf')
