/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Keyboard.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Keyboard(props) {
  const { nodes, materials } = useGLTF('/Keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={108702.826} decay={2} position={[0.014, 5.7, -4.183]} rotation={[-Math.PI / 2, 0, 0]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.895} position={[-7.677, 15.792, 12.783]} rotation={[-0.889, -0.358, -0.407]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Keyboard} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Silver} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Keycaps.geometry} material={materials.Keyboard} position={[-3.398, 0.175, -0.534]} scale={0.153} />
      <mesh geometry={nodes.Label_keys.geometry} material={materials['Letter Glow']} position={[-2.873, 0.303, 0.742]} scale={0.055} />
      <group position={[-0.233, 0.251, -0.092]} scale={0.152}>
        <mesh geometry={nodes.Sphere.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Keyboard.glb')
